#!/bin/sh
#             /usr/local/sbin/addblacklist <ip> <time> <name>
IP=$1
TIME=$2
NAME=$3
HOSTNAME=`hostname -f`
echo "INSERT INTO blacklist (ip, date, sourcehost, source) VALUES ('$IP', '$TIME', '$HOSTNAME', '$NAME');" | mysql rroethofsql1;
