#!/bin/sh
#sleep 10
DATABASE='domotica'
USER='domotia'
PASSWORD='xxx'
resultb=`mysql -h localhost --user=$USER --password=$PASSWORD --skip-column-names -e "SELECT DISTINCT source FROM $DATABASE.blacklist"`
itemsb=$(echo $resultb | tr " " "\n")

for itemb in $itemsb
do
    echo "- $itemb bans." 

    resulta=`mysql -h localhost --user=$USER --password=$PASSWORD --skip-column-names -e "SELECT DISTINCT ip FROM $DATABASE.blacklist WHERE source = '$itemb' ORDER BY ip"`
    itemsa=$(echo $resulta | tr " " "\n")
    for itema in $itemsa
    do
	if [ $itemb="import" ]; then
    	    echo "  - Blacklisting $itema for $itemb" 
    	    iptables -I fail2ban-ssh -s $itema -j DROP
	else
    	    echo "  - Blacklisting $itema for $itemb" 
    	    iptables -I fail2ban-$itemb -s $itema -j DROP
	fi
    done

done

